version: '3'

services:
  brand24:
    container_name: brand24
    image: ghcr.io/fafnir0007/brand24:latest
    environment:
      - CF_ACCESS_CLIENT_ID
      - CF_ACCESS_CLIENT_SECRET
      - DIRECTUS_TOKEN
      - DIRECTUS_HOST
      - MEILISEARCH_HOST
      - NEXT_PUBLIC_MEILI_SEARCH_KEY
    ports:
      - "3000:3000"
    restart: unless-stopped
