version: '3'

services:
  brand24:
    container_name: brand24
    build: .
    environment:
      - CF_ACCESS_CLIENT_ID
      - CF_ACCESS_CLIENT_SECRET
      - DIRECTUS_TOKEN
      - MEILISEARCH_HOST
      - DIRECTUS_HOST
      - NEXT_PUBLIC_MEILI_SEARCH_KEY
    ports:
      - "3000:3000"
    restart: unless-stopped
    labels:
      - traefik.enable=true
